FROM node:18-alpine as builder
WORKDIR /service

ARG LOCAL

COPY . /service

ENV NX_DAEMON=false

RUN npx nx run user:build --skip-nx-cache
RUN cp apps/user/.env dist/apps/user

FROM node:18-alpine

ARG LOCAL

WORKDIR /service

COPY --from=builder /service/package*.json /service/
COPY --from=builder /service/node_modules/ /service/node_modules/
COPY --from=builder /service/dist/apps/user /service/dist/

RUN cp ./dist/.env ./

USER node

CMD ["node", "dist/main.js"]
