apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: twitr-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /v1/user
            pathType: Prefix
            backend:
              service:
                name: twitr-user-service
                port:
                  number: 80
          - path: /v1/tweet
            pathType: Prefix
            backend:
              service:
                name: twitr-tweet-service
                port:
                  number: 80
          - path: /v1/timeline
            pathType: Prefix
            backend:
              service:
                name: twitr-timeline-service
                port:
                  number: 80
          - path: /v1/websockets
            pathType: Prefix
            backend:
              service:
                name: twitr-websocket-service
                port:
                  number: 80
